
import type { Metadata } from "next";
import "./globals.css";
import { ClientProviders } from "@/components/layout/ClientProviders";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "haowhite",
  icons: '/UserImage/up.jpg',
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      data-theme="dark"
      >
      <body
        className={` antialiased bg-image-[url('/bg.webp')]`}
      >

        <SessionProvider>
          <ClientProviders>
            {children}
          </ClientProviders>
        </SessionProvider>
      </body>
    </html>
  );
}
